### PR TITLE
Upgraded all intro-to-julia-for-data-science notebooks [ now compatible with Julia v1.0.0 ]

### PR DESCRIPTION
**Pull request by thatgeeman**
Previously the notebook was based on Julia v0.6.0
Updated **notebook 1** to incorporate changes forced by the recent stable release of Julia (v1.0.0)

_Changes_
 - Including Pkg.add() requirements to define packages needed
 - v1.0.0 updates (deprecated/old packages notification)
	- example: DataArrays
 - Date stamp added

### CODE REVIEW

**Comment by mbauman** [comment]
Nice, thanks!  This looks reasonable to me but let's wait until JuliaBox is up and running on 1.0… and maybe try to update the entire course at once so students aren't confused about switching back and forth between versions.

**Comment by thatgeeman** [comment]
@mbauman Yes this is underway. I will try to make another pull request with all changes soon. I could in fact close this one.

**Comment by thatgeeman** [comment]
@mbauman This is now ready for merging.

**Comment by thatgeeman** [comment]
Changed pull request to `revert-7-master` branch to avoid conflicts.

**Pull request closed without merging**
